
import React, { createContext, useContext, useState } from 'react';

type Language = 'ar' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'rtl' | 'ltr';
}

const translations = {
  ar: {
    'dashboard': 'لوحة القيادة',
    'students': 'الطلاب',
    'health': 'العيادة والصحة',
    'attendance': 'الحضور والغياب',
    'users': 'إدارة المستخدمين',
    'dining': 'الإطعام والمقصف',
    'settings': 'الإعدادات العامة',
    'activities': 'الحياة المدرسية',
    'academics': 'النتائج الدراسية',
    'maintenance': 'المرافق والصيانة',
    'behavior_tracking': 'تتبع السلوك',
    'logout': 'تسجيل الخروج',
    'developed_by': 'تم التطوير بواسطة',
    'welcome': 'أهلاً،',
    'admin': 'مدير',
    'supervisor': 'مشرف',
    'nurse': 'ممرض',
    'teacher': 'أستاذ',
    'parent': 'ولي أمر',
    'catering_manager': 'مسؤول المطعمة',
    'bursar': 'مسير المصالح المادية',
    'search': 'بحث...',
    'import': 'استيراد',
    'add_student': 'إضافة طالب',
    'save': 'حفظ التغييرات',
    'cancel': 'إلغاء',
    'total_students': 'مجموع التلاميذ',
    'attendance_rate': 'نسبة الحضور',
    'health_cases': 'حالات صحية',
    'room_status': 'حالة الغرف',
    'weekly_menu': 'برنامج الوجبات الأسبوعي',
    'breakfast': 'الفطور',
    'lunch': 'الغداء',
    'dinner': 'العشاء',
    'ftour': 'إفطار رمضان',
    'suhoor': 'السحور',
    'ramadan_mode': 'توقيت رمضان',
    'normal_mode': 'التوقيت العادي',
    'day': 'اليوم',
    'access_denied': 'غير مصرح لك بالوصول',
    'admin_only': 'هذه الصفحة خاصة بالمدير فقط',
    // Attendance & Exits
    'daily_attendance': 'الحضور اليومي',
    'weekly_exits': 'سجل الخرجات الأسبوعية',
    'register_exit': 'تسجيل خرجة جديدة',
    'exit_type': 'نوع الخرجة',
    'short_exit': 'خرجة قصيرة (سويعات)',
    'long_exit': 'خرجة طويلة (عطلة نهاية أسبوع)',
    'authorized_exit': 'غياب مرخص (بإذن الإدارة)',
    'return_date': 'تاريخ العودة',
    'start_date': 'تاريخ الخروج',
    'notes': 'ملاحظات',
    // Login & Settings
    'login_title': 'تسجيل الدخول',
    'login_subtitle': 'مرحباً بك في منصة مرافقة الرقمية',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'login_btn': 'دخول للمنصة',
    'institution_name': 'اسم المؤسسة',
    'school_year': 'الموسم الدراسي',
    'general_settings': 'إعدادات المنصة',
    'settings_desc': 'تعديل هوية المؤسسة والموسم الدراسي ومفاتيح الربط',
    'success_update': 'تم تحديث الإعدادات بنجاح',
    'api_settings': 'إعدادات الذكاء الاصطناعي',
    'connection_keys': 'مفاتيح الربط',
    'gemini_api_key': 'مفتاح Gemini API',
    'gemini_api_desc': 'يستخدم هذا المفتاح لتمكين ميزات الذكاء الاصطناعي مثل تحليل الصور والتقارير.',
    'key_placeholder': 'أدخل مفتاح الربط هنا...',
    // Dining Notification
    'notify_kitchen': 'إبلاغ المطعمة',
    'daily_count': 'العدد اليومي',
    'send_order': 'إرسال الطلبية',
    'message_sent': 'تم الإرسال بنجاح',
    'extra_meals': 'وجبات إضافية',
    // Activities
    'activities_title': 'سجل الأنشطة والحياة المدرسية',
    'activities_desc': 'تتبع الأنشطة الثقافية، الرياضية، والفعاليات التربوية.',
    'add_activity': 'إضافة نشاط',
    'upcoming_activities': 'أنشطة قادمة',
    'completed_activities': 'أنشطة منجزة',
    'activity_type': 'نوع النشاط',
    'organizer': 'المنظم',
    'location': 'المكان',
    'date_time': 'التاريخ والتوقيت',
    'sport': 'رياضي',
    'cultural': 'ثقافي',
    'religious': 'ديني',
    'educational': 'تربوي/تعليمي',
    'entertainment': 'ترفيهي',
    'participants': 'المشاركين',
    // Academics
    'academics_title': 'تتبع النتائج الدراسية',
    'academics_desc': 'تحليل نتائج الدورة الأولى والثانية، وتوزيع كشوف النقط.',
    'semester_1': 'الدورة الأولى',
    'semester_2': 'الدورة الثانية',
    'class_average': 'معدل القسم',
    'success_rate': 'نسبة النجاح',
    'top_student': 'المرتبة الأولى',
    'import_grades': 'استيراد النتائج (Excel)',
    'grade_distribution': 'توزيع المعدلات',
    'add_record': 'إضافة نتائج',
    'edit_record': 'تعديل النتائج',
    'subject': 'المادة',
    'grade': 'النقطة',
    'coefficient': 'المعامل',
    'decision': 'قرار المجلس',
    'appreciation': 'التقدير',
    'add_subject': 'إضافة مادة',
    // Maintenance
    'maintenance_title': 'المرافق والصيانة',
    'maintenance_desc': 'تتبع حالة المرافق، طلبات الإصلاح والتجهيز.',
    'add_request': 'طلب صيانة جديد',
    'pending_requests': 'طلبات معلقة',
    'in_progress': 'قيد الإنجاز',
    'completed': 'منجزة',
    'plumbing': 'سباكة (ماء)',
    'electricity': 'كهرباء',
    'cleaning': 'نظافة',
    'equipment': 'تجهيزات',
    'other': 'أخرى',
    'priority': 'الأولوية',
    'low': 'عادية',
    'medium': 'متوسطة',
    'high': 'عاجلة',
    'update_status': 'تحديث الحالة',
    // Behavior Tracking
    'behavior_title': 'تتبع السلوك والمواظبة',
    'behavior_desc': 'رصد السلوكات الإيجابية والسلبية للمتعلمين لتعزيز الانضباط.',
    'add_behavior': 'تسجيل سلوك',
    'positive_behavior': 'سلوك إيجابي',
    'negative_behavior': 'سلوك سلبي',
    'discipline': 'انضباط',
    'hygiene': 'نظافة وهندام',
    'interaction': 'تفاعل اجتماعي',
    'reporter': 'المبلغ',
    'incident_date': 'تاريخ الواقعة',
    'details': 'التفاصيل',
    'category': 'الفئة',
    'student_name': 'اسم التلميذ',
    'positive_count': 'إيجابي',
    'negative_count': 'سلبي',
    // Save Controls
    'unsaved_changes': 'توجد تغييرات غير محفوظة',
    'save_changes': 'حفظ التغييرات',
    'discard_changes': 'إلغاء التغييرات',
    'confirm_discard': 'هل أنت متأكد من إلغاء التغييرات؟ ستفقد البيانات غير المحفوظة.',
    'changes_saved': 'تم حفظ التغييرات بنجاح!'
  },
  fr: {
    'dashboard': 'Tableau de bord',
    'students': 'Élèves',
    'health': 'Infirmerie & Santé',
    'attendance': 'Présence & Absence',
    'users': 'Gestion des utilisateurs',
    'dining': 'Restauration',
    'settings': 'Paramètres Généraux',
    'activities': 'Vie Scolaire',
    'academics': 'Résultats Scolaires',
    'maintenance': 'Maintenance & Install.',
    'behavior_tracking': 'Suivi du Comportement',
    'logout': 'Se déconnecter',
    'developed_by': 'Développé par',
    'welcome': 'Bienvenue,',
    'admin': 'Directeur',
    'supervisor': 'Surveillant',
    'nurse': 'Infirmier',
    'teacher': 'Professeur',
    'parent': 'Parent',
    'catering_manager': 'Responsable Restauration',
    'bursar': 'Intendant',
    'search': 'Rechercher...',
    'import': 'Importer',
    'add_student': 'Ajouter élève',
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'total_students': 'Total Élèves',
    'attendance_rate': 'Taux de présence',
    'health_cases': 'Cas médicaux',
    'room_status': 'État des chambres',
    'weekly_menu': 'Menu Hebdomadaire',
    'breakfast': 'Petit Déjeuner',
    'lunch': 'Déjeuner',
    'dinner': 'Dîner',
    'ftour': 'Ftour (Ramadan)',
    'suhoor': 'Suhoor',
    'ramadan_mode': 'Mode Ramadan',
    'normal_mode': 'Mode Normal',
    'day': 'Jour',
    'access_denied': 'Accès refusé',
    'admin_only': 'Cette page est réservée à l\'administrateur',
    // Attendance & Exits
    'daily_attendance': 'Présence Quotidienne',
    'weekly_exits': 'Registre des Sorties',
    'register_exit': 'Enregistrer une sortie',
    'exit_type': 'Type de sortie',
    'short_exit': 'Sortie courte (Heures)',
    'long_exit': 'Sortie longue (Week-end)',
    'authorized_exit': 'Absence autorisée (Admin)',
    'return_date': 'Date de retour',
    'start_date': 'Date de sortie',
    'notes': 'Remarques',
    // Login & Settings
    'login_title': 'Connexion',
    'login_subtitle': 'Bienvenue sur la plateforme numérique Morafaka',
    'email': 'Email',
    'password': 'Mot de passe',
    'login_btn': 'Se connecter',
    'institution_name': 'Nom de l\'établissement',
    'school_year': 'Année scolaire',
    'general_settings': 'Paramètres de la plateforme',
    'settings_desc': 'Modifier l\'identité de l\'établissement et les clés API',
    'success_update': 'Paramètres mis à jour avec succès',
    'api_settings': 'Paramètres IA',
    'connection_keys': 'Clés de connexion',
    'gemini_api_key': 'Clé API Gemini',
    'gemini_api_desc': 'Cette clé est utilisée pour activer les fonctionnalités d\'IA telles que l\'analyse d\'images et les rapports.',
    'key_placeholder': 'Entrez la clé ici...',
    // Dining Notification
    'notify_kitchen': 'Informer la cuisine',
    'daily_count': 'Effectif du jour',
    'send_order': 'Envoyer la commande',
    'message_sent': 'Envoyé avec succès',
    'extra_meals': 'Repas supplémentaires',
    // Activities
    'activities_title': 'Activités et Vie Scolaire',
    'activities_desc': 'Suivi des activités culturelles, sportives et éducatives.',
    'add_activity': 'Ajouter activité',
    'upcoming_activities': 'Activités à venir',
    'completed_activities': 'Activités terminées',
    'activity_type': 'Type d\'activité',
    'organizer': 'Organisateur',
    'location': 'Lieu',
    'date_time': 'Date et Heure',
    'sport': 'Sport',
    'cultural': 'Culturel',
    'religious': 'Religieux',
    'educational': 'Éducatif',
    'entertainment': 'Divertissement',
    'participants': 'Participants',
    // Academics
    'academics_title': 'Suivi des Résultats',
    'academics_desc': 'Analyse des résultats S1 et S2, bulletins de notes.',
    'semester_1': '1er Semestre',
    'semester_2': '2ème Semestre',
    'class_average': 'Moyenne Classe',
    'success_rate': 'Taux de Réussite',
    'top_student': 'Premier Rang',
    'import_grades': 'Importer Notes (Excel)',
    'grade_distribution': 'Distribution des Notes',
    'add_record': 'Ajouter Résultats',
    'edit_record': 'Modifier Résultats',
    'subject': 'Matière',
    'grade': 'Note',
    'coefficient': 'Coefficient',
    'decision': 'Décision',
    'appreciation': 'Appréciation',
    'add_subject': 'Ajouter matière',
    // Maintenance
    'maintenance_title': 'Maintenance & Installations',
    'maintenance_desc': 'Suivi de l\'état des installations et demandes de réparation.',
    'add_request': 'Nouvelle demande',
    'pending_requests': 'En attente',
    'in_progress': 'En cours',
    'completed': 'Terminé',
    'plumbing': 'Plomberie',
    'electricity': 'Électricité',
    'cleaning': 'Nettoyage',
    'equipment': 'Équipement',
    'other': 'Autre',
    'priority': 'Priorité',
    'low': 'Normale',
    'medium': 'Moyenne',
    'high': 'Urgente',
    'update_status': 'Mettre à jour statut',
    // Behavior Tracking
    'behavior_title': 'Suivi du Comportement',
    'behavior_desc': 'Suivi des comportements positifs et négatifs pour renforcer la discipline.',
    'add_behavior': 'Signaler comportement',
    'positive_behavior': 'Comportement Positif',
    'negative_behavior': 'Comportement Négatif',
    'discipline': 'Discipline',
    'hygiene': 'Hygiène',
    'interaction': 'Interaction sociale',
    'reporter': 'Signalé par',
    'incident_date': 'Date de l\'incident',
    'details': 'Détails',
    'category': 'Catégorie',
    'student_name': 'Nom de l\'élève',
    'positive_count': 'Positif',
    'negative_count': 'Négatif',
    // Save Controls
    'unsaved_changes': 'Modifications non enregistrées',
    'save_changes': 'Enregistrer les modifications',
    'discard_changes': 'Annuler les modifications',
    'confirm_discard': 'Êtes-vous sûr de vouloir annuler ? Les données non enregistrées seront perdues.',
    'changes_saved': 'Modifications enregistrées avec succès !'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ar');

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['ar']] || key;
  };

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage,
      t,
      dir: language === 'ar' ? 'rtl' : 'ltr'
    }}>
      <div dir={language === 'ar' ? 'rtl' : 'ltr'} className={language === 'fr' ? 'font-sans' : 'font-tajawal'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
